pipeline {
    agent any
    tools {
        maven "maven3.9"
        jdk "jdk17"
    }
stages {
    stage('Fetch code'){
        steps{
            git branch:'atom', url:'https://github.com/hkhcoder/vprofile-project.git'
    }
    }

    stage('build'){
        steps{
            sh 'mvn install -DskipTests'
    }
        post{
            success{
                echo "Archiving artifact"
                archiveArtifacts artifacts: '**/*.war'
            }
        }
    }
    
    stage('Test'){
        steps{
            sh 'mvn test'
    }
    }   

    stage('checkstyle analysis'){
        steps{
            sh 'mvn checkstyle:checkstyle'
        }
    }
    stage("Sonar Code Analysis") {
        	environment {
                scannerHome = tool 'sonar6.2' // Creating a jenkins env variable scannerhome and seleting the sonar tool in jenkins config
            }
            steps {
              //Jenkins step that sets up the environment to interact with a SonarQube server,sonarserver is the name of the SonarQube server as defined in Jenkins config
              withSonarQubeEnv('sonarserver') {
                sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \  
                   -Dsonar.projectName=vprofile \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                // 1st line is the core command that triggers the analysis of your project by SonarQube,projecyKey is the name you are going to see on sonar server
                //sources is the source code
                //reportspath = path to reportes after running unit tests and other tests
                //binaries = path to complied code, here the complied code makes a new folder named target inside which we find complied test classes/ complied tests.
              }
            }
    stage("Quality gate"){
        steps{
            timeout(time: 1,unit: 'HOURS'){
                waitForQualityGate abortPipeline: true
            }
        }
    }
    stage("Upload artifact"){
        steps{
            nexusArtifactUploader(
            nexusVersion: 'nexus3',
            protocol: 'http',
            nexusUrl: '172.31.6.220:8081', //ip or url of server
            groupId: 'QA', //unique identifier for project
            version: "${env.BUILD_ID}-${en.BUILD_TIMESTAMP}", //dynamic versioning using inbuilt jenkins funcs.
            repository: 'vprofile', //name of the repo in nexus
            credentialsId: 'nexuslogin', //name of creds to access nexus which are configd in jenkins
            artifacts: [
                [artifactId: 'vproapp',
                classifier: '',
                file: 'target/vprofile-v2.war', //path to the artifact
                type: 'war']
        ]
     )
        }
    }
}
}
